### PR TITLE
On Debian Jessie, the nfsv4 client uses nfs-common as a wrapper for r…

### PR DESCRIPTION
**Pull request by kwisatz**
…pc services (e.g. idmapd) to start

See https://github.com/derdanne/puppet-nfs/issues/57

### CODE REVIEW

**Comment by derdanne** [comment]
Thanks for the PR! Can you please fix the spec tests?

**Comment by kwisatz** [comment]
@derdanne Oops, sorry, hadn't noticed they had failed. Will fix them ASAP.

**Comment by kwisatz** [comment]
@derdanne They don't seem to be related to my changes. I reverted back to b6d16eb74467fe8b25a2dd727760c3881079b7f6 and the same tests are failing. 

It would appear that "undef" is no longer being cast to [] but to [nil] by puppet or one of the modules. When I change `$subscription = undef` to `$subscription = []` in client.pp, then all tests pass.

**Comment by derdanne** [comment]
ok, thanks for the analysis, i will check that - seems related to an updated gem.

**Pull request merged**
