### PR TITLE
Features for better managing services and packages

### PR DESCRIPTION
**Pull request by derdanne**
added puppet-syntax gem to Gemfile
added new parameters server_package_ensure, manage_server_service, manage_server_servicehelper, manage_client_service  for better managing service and packages

### CODE REVIEW

**Comment by tampakrap** [comment]
amazing thanks! can we have also the packages to trigger services restart?

**Comment by derdanne** [comment]
Hey, i've pushed the needed changes to https://github.com/derdanne/puppet-nfs/tree/feature_notify_services_from_packages.

Could you please verify the patch.

**Comment by tampakrap** [comment]
sure checking

**Comment by tampakrap** [comment]
client/server_package_ensure remove the validation please. It can be also a version

**Comment by derdanne** [comment]
We can remove it for server packages, client packages will be in most cases an array, where versions of each package do not necessarily match.

**Comment by derdanne** [comment]
Oh, i see that this also counts for the server packages ... i have to rethink this, maybe we need anothe solution here

**Comment by derdanne** [comment]
I opened a new issue for that problem: #37

**Comment by tampakrap** [comment]
`$notify_services = suffix(prefix(keys($::nfs::effective_nfsv4_client_services), 'Service[\''), '\']')`

this is too complex. Service can take an array as argument iirc, so it can be simplified to `Service[keys($::nfs::effective...)]`. But I'm not 100% sure about this, need to verify it first

**Comment by derdanne** [comment]
Yes, but i thought this is not compatible with older puppet versions, but maybe i am wrong - just had it in my mind ...

**Comment by derdanne** [comment]
Just checked: 

https://docs.puppet.com/puppet/latest/reference/lang_data_resource_reference.html#multi-resource-references

So your approach should be fine!

**Comment by derdanne** [comment]
@tampakrap 

Hey, the best way should be to manage package versions (if needed) outside the module, so i think of a manage_package switch - so you can completely define the packages yourself.

What do you think? Any better approach?

**Comment by tampakrap** [comment]
The manage_package switch is fine and would be a step forward, but it does not solve entirely the problem. The appropriate approach would be to create different variables for each package unfortunately, but I understand that there is quite a variety of package names along the distros, as seen in params.pp. So what I would suggest is just to remove the validation for the package_ensure, and let the users overwrite the package list in their profile module if they want to override stuff.

As an example, I did it in my infrastructure. I am using osfamily suse, and I removed nfsidmap and rpcbind from the client_packages array, as they are properly pulled in by my package manager. In case I would like to lock their versions in the future I can do it in my profile module (same for client_packages, which is only 'nfs-client' for me now, assuming the validation wouldn't be there).

Does that make sense?

**Comment by tampakrap** [comment]
Another idea that I just thought of: let server_packages and client_packages contain only the necessary packages and their subpackages, and create variables like server_pkg_dependencies to provide an array of packages as dependencies (controlled by a server_pkg_deps_manage switch). I don't like this idea very much though, as the _pkg_dependencies packages will have exactly the same issue that we are trying to solve. Tbh I would just remove the validation and let users figure it out themselves from then

**Comment by derdanne** [comment]
OK, ithink i will do both, i will set the validation for the package_ensure to string and i will add a manage_package switch, so the user has the full control, and can do whatever he wants do do.

**Pull request merged**
