### PR TITLE
Insert nfs4_disable_idmapping to enable idmapping for sec=sys

### PR DESCRIPTION
**Pull request by SR-mkuhn**
Please review these change request thoroughly, as i've never worked with augeas and didn't had the means to test it.

### CODE REVIEW

**Comment by SR-mkuhn** [comment]
basically this https://unix.stackexchange.com/questions/438939/how-to-get-nfsv4-idmap-working-with-sec-sys

**Comment by derdanne** [comment]
Hey @SR-mkuhn, thanks for the pull request. 

Please check the following comments :)

1.) Make sure that all filepaths which could be distribution specific are defined inside the params.pp (i.e. /etc/modprobe.d/nfs.conf)

2.) Have a look at the Travis-CI testing failures, and make sure you fix all failures, which are introduced with this PR

3.) When you have changes which affects clients and servers, make sure we do not get any double declarations, when acting on both roles (i.e. your file declaration: file {'/etc/modprobe.d/nfs.conf' .. )

4.) Try to add a spec test for your patch (if possible)

PS:
You can test the PR on your local box before pushing and waiting for Travis-CI. Have a look at https://github.com/derdanne/puppet-nfs#development

When you need support, please checkout the very helpful Puppet Community Slack (where you can also  contact me via PM)

**Comment by SR-mkuhn** [comment]
Sorry i've not the means to follow this issue any further (I would like to, but not the right knowledge, tooling and time on my end)

**Comment by derdanne** [comment]
That is very sad! My intention was not to demotivate you.

**Comment by SR-mkuhn** [comment]
You didn't. Anyway, i just learned, that idmapping foo is broken as hell.
https://dfusion.com.au/wiki/tiki-index.php?page=Why+NFSv4+UID+mapping+breaks+with+AUTH_UNIX

**Pull request closed without merging**
