### PR TITLE
Migrate to Puppet 4

### PR DESCRIPTION
**Pull request by bastelfreak**
This gets rid of all the legacy validate_* function calls and replaces them with proper data types.

### CODE REVIEW

**Comment by bastelfreak** [comment]
The rubocop config/Gemfile is a bit outdated.  If you want I can apply the same settings as we use in the puppet community, for example here: https://github.com/voxpupuli/puppet-zabbix

The rubocop issues are all based on existing code, let me how how I should deal with them.

**Comment by derdanne** [comment]
Thanks for the PR.

On the Rubocop side we can apply the ruleset you mentioned above. Did you check the new Rubocop ruleset locally? Are there any other issues with the existing code? 

To have the existing code pass the test, we should disable/modify the checks, and mark it as "TODO", to rewrite the concerning tests.

In example we could disable the "Metrics/BlockLength" to not have the issues the ci is currently noting:
`Metrics/BlockLength:
   Enabled: false`

**Comment by warrenpnz** [comment]
I understand the object of this PR, but then does it not make it P4 exclusive and anyone running P3 or less would then be unsupported? I do have clients using this module in P4 and 3 envs, which might require migrating to a different module

**Comment by bastelfreak** [comment]
@warrenpnz yes, this will drop puppet3 support. Puppet4 is around since a very long time, also Puppet3 supported ended last december. Vox Pupuli dropped puppet3 with be beginning of 2017: https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/

Also puppetlabs is dropping puppet3 on more and more modules.

**Comment by warrenpnz** [comment]
Hmmm...seems a bit premature given that RH Satellite 6 still uses 3.8.6. Still such is progress

**Comment by bastelfreak** [comment]
Sadly, RedHat is famous for shipping legacy outdated software :(

If you need help with migrating between puppet version, feel free to join the #voxpupuli IRC channel. We provide help 24/7

**Comment by derdanne** [comment]
I understand the demand for Puppet 3 compatible modules on Redhat Satellite 6. I tend to release a new major version 2.x.x and drop puppet 3 support with it, so if anybody wants to use this module on puppet 3 nodes, he can use the current major branch 1.x and users with demand for puppet 4 modules can use the releases in the 2.x branch. I will also add a prominent warning in the README.

In the future we could backport only major bugfixes to the 1.x branch. Since the module is very stable with the current code base, i do not expect that there will be that much work to do on this side.

We could also continue the developement on this module regardless doing work on backporting code to puppet 3.

@warrenpnz @bastelfreak 
Do you think that would be a viable solution for you?

**Comment by bastelfreak** [comment]
@derdanne I applied a few of the Vox Pupuli configs and fixed the rubocop errors.

**Pull request merged**
